#!/bin/bash
sed s/cup/union/g $1 | 
sed s/rrrr/"<<r r r r>> as BaseRelation72"/g |
sed s/rrrl/"<<r r r l>> as BaseRelation72"/g |
sed s/rrlr/"<<r r l r>> as BaseRelation72"/g |
sed s/rrll/"<<r r l l>> as BaseRelation72"/g |
sed s/rlrr/"<<r l r r>> as BaseRelation72"/g |
sed s/rllr/"<<r l l r>> as BaseRelation72"/g |
sed s/rlll/"<<r l l l>> as BaseRelation72"/g |
sed s/lrrr/"<<l r r r>> as BaseRelation72"/g |
sed s/lrrl/"<<l r r l>> as BaseRelation72"/g |
sed s/lrll/"<<l r l l>> as BaseRelation72"/g |
sed s/llrr/"<<l l r r>> as BaseRelation72"/g |
sed s/llrl/"<<l l r l>> as BaseRelation72"/g |
sed s/lllr/"<<l l l r>> as BaseRelation72"/g |
sed s/llll/"<<l l l l>> as BaseRelation72"/g |
sed s/ells/"<<e l l s>> as BaseRelation72"/g |
sed s/eses/"<<e s e s>> as BaseRelation72"/g |
sed s/errs/"<<e r r s>> as BaseRelation72"/g |
sed s/lere/"<<l e r e>> as BaseRelation72"/g |
sed s/rele/"<<r e l e>> as BaseRelation72"/g |
sed s/slsr/"<<s l s r>> as BaseRelation72"/g |
sed s/srsl/"<<s r s l>> as BaseRelation72"/g |
sed s/lsel/"<<l s e l>> as BaseRelation72"/g |
sed s/rser/"<<r s e r>> as BaseRelation72"/g |
sed s/sese/"<<s e s e>> as BaseRelation72"/g |

sed s/ffbb/"<<f f b b>> as BaseRelation72"/g |
sed s/efbs/"<<e f b s>> as BaseRelation72"/g |
sed s/ifbi/"<<i f b i>> as BaseRelation72"/g |
sed s/bfii/"<<b f i i>> as BaseRelation72"/g |
sed s/sfsi/"<<s f s i>> as BaseRelation72"/g |
sed s/beie/"<<b e i e>> as BaseRelation72"/g |
sed s/bbff/"<<b b f f>> as BaseRelation72"/g |
sed s/bsef/"<<b s e f>> as BaseRelation72"/g |
sed s/biif/"<<b i i f>> as BaseRelation72"/g |
sed s/iibf/"<<i i b f>> as BaseRelation72"/g |
sed s/sisf/"<<s i s f>> as BaseRelation72"/g |
sed s/iebe/"<<i e b e>> as BaseRelation72"/g |
sed s/ffff/"<<f f f f>> as BaseRelation72"/g |
sed s/fefe/"<<f e f e>> as BaseRelation72"/g |
sed s/fifi/"<<f i f i>> as BaseRelation72"/g |
sed s/fbii/"<<f b i i>> as BaseRelation72"/g |
sed s/fsei/"<<f s e i>> as BaseRelation72"/g |
sed s/ebis/"<<e b i s>> as BaseRelation72"/g |
sed s/iifb/"<<i i f b>> as BaseRelation72"/g |
sed s/eifs/"<<e i f s>> as BaseRelation72"/g |
sed s/iseb/"<<i s e b>> as BaseRelation72"/g |
sed s/bbbb/"<<b b b b>> as BaseRelation72"/g |
sed s/sbsb/"<<s b s b>> as BaseRelation72"/g |
sed s/ibib/"<<i b i b>> as BaseRelation72"/g |
sed s/lllb/"<<l l l b>> as BaseRelation72"/g |
sed s/llfl/"<<l l f l>> as BaseRelation72"/g |
sed s/llbr/"<<l l b r>> as BaseRelation72"/g |
sed s/llrf/"<<l l r f>> as BaseRelation72"/g |
sed s/lirl/"<<l i r l>> as BaseRelation72"/g |
sed s/lfrr/"<<l f r r>> as BaseRelation72"/g |
sed s/lril/"<<l r i l>> as BaseRelation72"/g |
sed s/lrri/"<<l r r i>> as BaseRelation72"/g |
sed s/blrr/"<<b l r r>> as BaseRelation72"/g |
sed s/irrl/"<<i r r l>> as BaseRelation72"/g |
sed s/frrr/"<<f r r r>> as BaseRelation72"/g |
sed s/rbrr/"<<r b r r>> as BaseRelation72"/g |
sed s/lbll/"<<l b l l>> as BaseRelation72"/g |
sed s/flll/"<<f l l l>> as BaseRelation72"/g |
sed s/brll/"<<b r l l>> as BaseRelation72"/g |
sed s/rfll/"<<r f l l>> as BaseRelation72"/g |
sed s/rlli/"<<r l l i>> as BaseRelation72"/g |
sed s/rrlf/"<<r r l f>> as BaseRelation72"/g |
sed s/illr/"<<i l l r>> as BaseRelation72"/g |
sed s/rilr/"<<r i l r>> as BaseRelation72"/g |
sed s/rrbl/"<<r r b l>> as BaseRelation72"/g |
sed s/rlir/"<<r l i r>> as BaseRelation72"/g |
sed s/rrfr/"<<r r f r>> as BaseRelation72"/g |
sed s/rrrb/"<<r r r b>> as BaseRelation72"/g 
